export { default as Navbar } from './navbar/Navbar'
export { default as Hero } from './hero/Hero'
export { default as Iam } from './iam/Iam'
export { default as Skills } from './skills/Skills'
export { default as Layout } from './Layout'
export { default as Bio } from './bio/Bio'
